### ISSUE TITLE
Add locations for code samples

### ISSUE THREAD

**Issue by smbdelse** [inertiajs/inertiajs.com#12]
Hi!

Whenever there is some code sample in docs it would be great to have also some information about where to put it. I always find it confusing when there is a code explanation and no info about file name or location is provided. Especially, when description starts from "you **simply** need to" ;)

For example "Configuring" paragraph of https://inertiajs.com/asset-versioning page

**Comment by Juhlinus** [comment]
This is a good point, @smbdelse, thanks for creating the issue.

I have some follow-up questions:

1. Do you have this issue in the case of the front-end adapter examples as well?
2. What back-end adapter are you using?
3. How familiar are you with said back-end framework?

In my case when I see an example like the one in the asset-versioning page, then my brain defaults to the following(I'm using Laravel):

- Do I have any need for this?
- If I have any need for it, is it needed on every request?
- If yes, then putting it in a model or controller is out of the question.
- What is something that gets run every request in the framework?
- A serviceprovider might be a good fit.
- Is this something that is being done in the PingCRM app, perhaps?
- Check the PingCRM example app.

So, instead of specifying a specific file, maybe we should make sure that a relevant example is present in the PingCRM example app and reference the specific line that's relevant.

@reinink thoughts?

**Comment by smbdelse** [comment]
Thank you for the answer @Juhlinus 

from 1 to 3:
Well, I wouldn't call it an issue, because being familiar with the tool (Vue+Laravel in my case) makes it easy to decide where and how to use snippets shown in the documentation. But I can imagine that there could be pretty big group of people who could benefit from knowing not only "what" and "how", but also "where". And still, even being familiar with framework creates in this case unnecessary cognitive burden.

About the process you described, thanks for sharing, that are some good points to consider!

PingCRM is great as an example, but I think that simple statement "usually in filename.php" is also a good clue.

**Comment by reinink** [comment]
I agree @smbdelse, good call. I've been actively trying to do this better. I'm going to close this issue, but will continue to keep this in mind for the future. 👍
