### ISSUE TITLE
To-Do List?

### ISSUE THREAD

**Issue by Juhlinus** [inertiajs/inertiajs.com#2]
Do you have any to-do list that you're following, right now?

I'd love to help out with writing what part of the docs I feel comfortable writing, but at the same time I don't want to sit down and write something that is already almost completely done.

**Comment by Nothing-Works** [comment]
@reinink any update for the doc? or anything we may help?

**Comment by reinink** [comment]
Sorry folks, no todo list now. I very much appreciate the offer, but at this point I think I'd like to grind it out and write the first iteration of the docs. This is largely because I am still figuring out the overall structure.

Once I have the first iteration done, I'd very much appreciate help improving on them.

Thanks for the offer! 🙏
