### ISSUE TITLE
Proper Admin Template

### ISSUE THREAD

**Issue by nnnayeem** [inertiajs/inertiajs.com#61]
Hello,

This is not a issue. I just want suggestion regarding using inertia. I have been using inertia with bootstrap for learning in laravel and I felt the overall experience is great. I am also mentioning that I am new to vue.

In my recent project I am going to implement Inertia but it seems most of the vue template are used for vue-router not for inertia and I am facing problem implementing them. It seems I have to edit lots of files in order to implement.

I want suggestion in this regard that what is the proper way to implement a vue template to laravel using inertia js instead of vue router.

You can give me suggestion or give me any resource.

**Comment by Neophen** [comment]
There is [ping crm](https://github.com/inertiajs/pingcrm)

**Comment by claudiodekker** [comment]
Yeah, PingCRM is indeed a very good example of a full application, but I'd like to add that [the documentation on our website](https://inertiajs.com/) has some great examples as well, so I'd recommend to start there.

As for [routing](https://inertiajs.com/routing) in Laravel specifically: The [Ziggy](https://github.com/tightenco/ziggy) library can help you with this, as it makes your routes available to your front-end automatically via a global route() function. 

Since you indicate to be using Vue.js, it's helpful to make this function available as a custom `$route` property so you can use it directly in your templates. You can do this by adding the following line _before_ you initialize Inertia / the Vue application in your `app.js`:

```js
Vue.prototype.$route = (...args) => route(...args).url()
```

Then, you may use the `$route` helper as follows:
```html
<inertia-link :href="$route('users.create')">Create User</inertia-link>
```

Hope this helps!

**Comment by heposoft** [comment]
#thanks

**Comment by reinink** [comment]
Sounds like this has been resolved. Closing this. 👍
